### ISSUE TITLE
GitHub releases with multiple files only show the first one

### ISSUE THREAD

**Issue by Epicpkmn11** [BrewShop/BrewShopNitro#5]
pkmn-chest links the `.cia` build instead of the `.nds` build, if you want me to change how it does the URL on the back end let me know how you want it (I gave an example how how might work well in #1), or maybe splitting the button or asking the user somehow could be good

**Comment by Multimegamander** [comment]
Could you change releases to be a .zip containing the .cia and .nds perhaps, unless you want to approach it a different way? eg. adding a popup box that shows all downloads?

**Comment by Epicpkmn11** [comment]
> Could you change releases to be a .zip containing the .cia and .nds perhaps, unless you want to approach it a different way?

I prefer to have them separate since it makes it easier if you just want the `pkmn-chest.nds` I think...
Also GBARunner2 only shows the 3DS file right now

> eg. adding a popup box that shows all downloads?

Yeah, if that's not too hard to do I think showing a popup if there's multiple files would be nice, or maybe showing multiple links, though I'm not sure how well that'd work with the grid, especially with GBARunner2's four files

**Comment by Multimegamander** [comment]
It would change the downloads for all the homebrew, but instead of auto downloading, I could implement a modal box that lists all the downloads, it would require updating to the python script to grab every release binary tho

**Comment by Epicpkmn11** [comment]
> it would require updating to the python script to grab every release binary tho 

It already has them all in an array, I just edited the html to force the first as a temporary fix-ish, is this good? (prettified from current `list0.json`):
```json
    "files":
        [
            {
                "name": "GBARunner2_arm7dldi_3ds.nds",
                "size": 263744,
                "url": "https://github.com/Gericom/GBARunner2/releases/download/v20200216-165624_c417fd0/GBARunner2_arm7dldi_3ds.nds"
            },
            {
                "name": "GBARunner2_arm7dldi_ds.nds",
                "size": 263744,
                "url": "https://github.com/Gericom/GBARunner2/releases/download/v20200216-165624_c417fd0/GBARunner2_arm7dldi_ds.nds"
            },
            {
                "name": "GBARunner2_arm7dldi_dsi.nds",
                "size": 263744,
                "url": "https://github.com/Gericom/GBARunner2/releases/download/v20200216-165624_c417fd0/GBARunner2_arm7dldi_dsi.nds"
            },
            {
                "name": "GBARunner2_arm9dldi_ds.nds",
                "size": 262720,
                "url": "https://github.com/Gericom/GBARunner2/releases/download/v20200216-165624_c417fd0/GBARunner2_arm9dldi_ds.nds"
            }
        ],
```

**Comment by Multimegamander** [comment]
Oh, I didn't see that, fixing this will be easier than I thought, lol

**Comment by Multimegamander** [comment]
fixed
